export const STORAGE_KEYS = {
  initialized: 'ams_initialized_v1',
  assets: 'ams_assets',
  departments: 'ams_departments',
  subDepartments: 'ams_sub_departments',
  buildings: 'ams_buildings',
  floors: 'ams_floors',
  rooms: 'ams_rooms',
  categories: 'ams_categories',
  assetTypes: 'ams_asset_types',
  users: 'ams_users',
  assignments: 'ams_assignments',
  transfers: 'ams_transfers',
  maintenance: 'ams_maintenance',
  schedules: 'ams_schedules',
  requests: 'ams_requests',
  receiving: 'ams_receiving',
  verificationSessions: 'ams_verification_sessions',
  verificationLines: 'ams_verification_lines',
  disposals: 'ams_disposals',
  documents: 'ams_documents',
  timelines: 'ams_timelines',
  notifications: 'ams_notifications',
  auditLogs: 'ams_audit_logs',
  savedViews: 'ams_saved_views',
  settings: 'ams_settings',
  currentUserId: 'ams_current_user_id',
} as const
